### ISSUE TITLE
移行要件一覧表示機能について

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/scs-migration-checker#13]
* 英語、フレッシュマンセミナー、情報といった、クラスや履修班によって時限が異なる授業で、授業名がJSONから一番初めに名前検索がヒットした授業の時限が表示されてしまいます

* 看護学類がとらなければいけない日本国憲法の時限が秋AB 金4,5となっていますが、その授業は看護学類対象の授業ではなくて、正しくは夏季休業中の授業です
* 線形代数Aについても、同じ名前で2年次向けの、別の線形代数が表示されています

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/scs-migration-checker/commit/9fa9697a0bac8a31b48c7969b5e83e7094f0de50

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/scs-migration-checker/commit/a733d9ce38554ea9f748834415fc3712d22481f3
