### ISSUE TITLE
ステップ2で空きコマに授業を登録できない

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/scs-migration-checker#21]
![image](https://user-images.githubusercontent.com/80367947/159490199-0b85c2ff-5828-4f20-b918-5de0990989de.png)
ステップ2で授業の登録ボタンを押すと発生 (ステップ1で登録した授業をステップ2で削除→再登録する場合はエラーは起きなかった)
調べてみたけどgetSeasonarrayの引数のKdBDataの中身が壊れていそう  
一応エラーメッセージも添付しておきます

**Comment by itsu-dev** [comment]
ありがとう！！リファクタリングの時にミスってたっぽい
https://github.com/itsu-dev/scs-migration-checker/pull/22/commits/66cc7bf099930d11a867aa1e4b623adf4bd07601
