### ISSUE TITLE
看護学類の移行条件について

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/scs-migration-checker#7]
いくつか気になる点があったので
* 国語I が条件に含まれていません
* 紫の冊子で、英語を2単位とったとして、応募要件の単位数の合計を計算すると26となるため、最低単位数が30だと判定が正しく表示されないと思います。(応募要件をすべて満たした仮組みでテストしましたが応募要件を満たしてないと表示されました）
* 日本国憲法の単位数は1ではなくて2だと思います

**Comment by itsu-dev** [comment]
ありがとうございます。確認後、修正いたします！

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/scs-migration-checker/commit/b4010ce7be5464df7dc058214b6ca8925cdb32b1
